FROM node:18-alpine AS builder
WORKDIR /app
EXPOSE 3000
COPY . .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:latest as server

RUN sed -i "s/80/3000/g" /etc/nginx/conf.d/default.conf

COPY --from=builder /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]