services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chess-api
      - chess-ui
    ports:
      - 7800:7800
  database:
    container_name: chess-database
    image: postgres:14.1
    restart: "no"
    env_file:
      - database.env
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
  chess-api:
    build: chess-api
    image: chess-api
    restart: "no"
    volumes:
      - ./chess-api/:/app
    expose:
      - 8000
    depends_on:
      - redis
      - database
    env_file:
      - database.env
  chess-ui:
    build: chess-ui
    image: chess-ui
    restart: "no"
    volumes:
      - ./chess-ui:/app
    expose:
      - 3000
    depends_on:
      - chess-api
