services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chess-api
      - chess-ui
    ports:
      - 7800:7800
  database:
    container_name: chess-database
    image: postgres:14.1
    restart: "no"
    env_file:
      - database.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      interval: 5s
      timeout: 5s
      retries: 5
  chess-api:
    build: chess-api
    image: chess-api
    restart: "no"
    volumes:
      - ./chess-api/:/app
    expose:
      - 8000
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - database.env
  chess-ui:
    build: chess-ui
    image: chess-ui
    restart: "no"
    volumes:
      - ./chess-ui:/app
    expose:
      - 3000
    depends_on:
      - chess-api
