services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chess-api
      - chess-ui
    ports:
      - 7800:7800
  database:
    container_name: chess-database
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - ./production-database-data:/var/lib/postgresql/data
    env_file:
      - database.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      interval: 5s
      timeout: 5s
      retries: 5
  chess-api:
    build:
      context: chess-api
      dockerfile: Dockerfile.prod
    image: chess-api
    restart: "on-failure"
    volumes:
      - ./chess-api/:/app
    expose:
      - 8000
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - database.env
  chess-ui:
    build: 
      context: chess-ui
      dockerfile: Dockerfile.prod
    image: chess-ui-prod
    restart: "on-failure"
    volumes:
      - ./chess-ui:/app
    expose:
      - 3000
    depends_on:
      - chess-api
