CREATE TYPE GAME_STATUS AS ENUM ('ONGOING', 'ENDED');
CREATE TYPE GAME_ENGINE AS ENUM ('ALPHABETA', 'MINMAX','RANDOM');

CREATE TABLE game (
  id SERIAL PRIMARY KEY,
  user_uuid TEXT NOT NULL,
  status GAME_STATUS NOT NULL DEFAULT 'ONGOING',
  fen TEXT NOT NULL,
  engine GAME_ENGINE NOT NULL DEFAULT 'RANDOM',
  draw BOOLEAN,
  winner TEXT
);